# Generated by Django 4.2.7 on 2023-11-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=9)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nro_celular', models.CharField(max_length=9)),
                ('direccion', models.TextField()),
                ('ramos_a_cursar', models.IntegerField()),
            ],
        ),
    ]
