# Generated by Django 4.2.7 on 2023-11-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=9)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nro_celular', models.CharField(max_length=9)),
                ('direccion', models.TextField()),
                ('ramos_a_impartir', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cantidad_notas', models.CharField(max_length=9)),
                ('estado', models.BooleanField()),
                ('fecha_inicio', models.TextField()),
                ('fecha_termino', models.TextField(max_length=9)),
                ('numero_horas', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ramos_a_cursar',
            field=models.PositiveIntegerField(),
        ),
    ]
